[package]
name = "host"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "zkstark_dec_verifier"
path = "src/verifier.rs"

[[bin]]
name = "zkstark_dec_prover"
path = "src/main.rs"

[dependencies]
methods = { path = "../methods" }
risc0-zkvm = { version = "^2.1.0" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = "1.0"
json = "0.12"
bincode = "1.3"