[package]
name = "zkp_bulletproofs"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "zkbp_enc"
path = "src/enc.rs"

[[bin]]
name = "zkbp_dec"
path = "src/dec.rs"

[dependencies]
bulletproofs = { git = "https://github.com/dalek-cryptography/bulletproofs", rev = "464acb7", features = ["std", "avx2_backend", "yoloproofs"] }
curve25519-dalek = { version = "3", default-features = false, features = ["u64_backend", "serde"] }
merlin = { version = "2", default-features = false }
rand = { version = "0.7", default-features = false }
json = "0.12"