// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use methods::ZKP_DEC_ELF;
use risc0_zkvm::{default_prover, ExecutorEnv};
use std::{error::Error, fs, path::PathBuf, env, time::Instant};

fn main() -> Result<(), Box<dyn Error>>{
    // use executable as: ./prover m l k data_path proof_path
    let args: Vec<String> = env::args().collect();
    let m : usize = args[1].parse().unwrap();
    let l : usize = args[2].parse().unwrap();
    let k : usize = args[3].parse().unwrap();
    let data_path = &args[4];
    let proof_path = &args[5];

    // read the JSON data to vector
    let data = fs::read_to_string(PathBuf::from(data_path))?;
    let data = json::parse(&data).unwrap();

    // init the vectors
    let mut s : Vec<Vec<u32>> = Vec::new();
    let mut c : Vec<u32> = Vec::new();
    let mut d : Vec<u32> = Vec::new();

    // load the data from JSON
    for i in 0..k{
        c.push(data["c_1"][i].as_u32().unwrap());
    }
    for i in 0..m*l{
        d.push(data["d_i"][i].as_u32().unwrap());
        let mut row_s : Vec<u32> = Vec::new();
        for j in 0..k{
            row_s.push(data["s_i"][i][j].as_u32().unwrap());
        }
        s.push(row_s);
    }

    // setup input
    let input : (Vec<Vec<u32>>, Vec<u32>, Vec<u32>) = (s, c, d);
    let env = ExecutorEnv::builder()
        .write(&input)
        .unwrap()
        .build()
        .unwrap();
    
    // obtain the default prover.
    let prover = default_prover();

    let now = Instant::now();
    // produce a receipt by proving the specified ELF binary.
    let receipt = prover.prove(env, ZKP_DEC_ELF).unwrap().receipt;
    let elapsed = now.elapsed();
    println!("ZKP STARK Dec Prove: {:.2?} ms", elapsed.as_millis());

    // output the receipt to a file
    let output_path = PathBuf::from(proof_path);
    let bin = bincode::serialize(&receipt).unwrap();
    fs::write(output_path, &bin)?;
    println!("ZKP STARK Dec Size: {} bytes", bin.len());

    Ok(())
}
