// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use methods::ZKP_DEC_ID;
use std::{error::Error, fs, path::PathBuf, env, time::Instant};
use risc0_zkvm::Receipt;

fn main() -> Result<(), Box<dyn Error>>{
    // use executable as: ./verifier m l k data_path proof_path
    let args: Vec<String> = env::args().collect();
    let m : usize = args[1].parse().unwrap();
    let l : usize = args[2].parse().unwrap();
    let _k : usize = args[3].parse().unwrap();
    let data_path = &args[4];
    let proof_path = &args[5];

    // read the JSON data to vector
    let data = fs::read_to_string(PathBuf::from(data_path))?;
    let data = json::parse(&data).unwrap();

    // init the vectors
    let mut x : Vec<u32> = Vec::new();

    // load the data from JSON
    for i in 0..m*l{
        x.push(data["x_i"][i].as_u32().unwrap());
    }

    // load the receipt file
    let receipt_data = fs::read(PathBuf::from(proof_path)).unwrap();
    let receipt: Receipt = bincode::deserialize(&receipt_data).unwrap();

    let now = Instant::now();
    // verify the receipt file
    receipt.verify(ZKP_DEC_ID).expect("Verification failed!");
    let elapsed = now.elapsed();
    println!("ZKP STARK Enc Verify: {:.2?} ms", elapsed.as_millis());

    // compare the results
    // let x_i = receipt.journal.decode::<Vec<u32>>().unwrap();
    // if x_i == x {
    //     println!("Decryption verified!");
    // } else {
    //     println!("Decryption verification failed: results do not match!");
    // }
    Ok(())
}
