// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use methods::ZKP_ENC_ELF;
use risc0_zkvm::{default_prover, ExecutorEnv};
use std::{error::Error, fs, path::PathBuf, env, time::Instant};

fn main() -> Result<(), Box<dyn Error>>{
    // use executable as: ./prover m l k data_path proof_path
    let args: Vec<String> = env::args().collect();
    let m : usize = args[1].parse().unwrap();
    let l : usize = args[2].parse().unwrap();
    let k : usize = args[3].parse().unwrap();
    let data_path = &args[4];
    let proof_path = &args[5];

    // read the JSON data to vector
    let data = fs::read_to_string(PathBuf::from(data_path))?;
    let data = json::parse(&data).unwrap();

    // init the vectors
    let mut a : Vec<Vec<u32>> = Vec::new();
    let mut b : Vec<Vec<u32>> = Vec::new();
    let mut e1 : Vec<u32> = Vec::new();
    let mut e2 : Vec<u32> = Vec::new();
    let mut r : Vec<u32> = Vec::new();
    let mut x : Vec<u32> = Vec::new();

    // load the data from JSON
    for i in 0..k{
        r.push(data["r"][i].as_u32().unwrap());
        e1.push(data["e_1"][i].as_u32().unwrap());
        let mut row_a : Vec<u32> = Vec::new();
        for j in 0..k{
            row_a.push(data["A"][i][j].as_u32().unwrap());
        }
        a.push(row_a);
    }
    for i in 0..m*l{
        x.push(data["priv_key"][i].as_u32().unwrap());
        e2.push(data["e_2"][i].as_u32().unwrap());
        let mut row_b : Vec<u32> = Vec::new();
        for j in 0..k{
            row_b.push(data["B"][i][j].as_u32().unwrap());
        }
        b.push(row_b);
    }

    // setup input
    let input : (Vec<Vec<u32>>, Vec<Vec<u32>>, Vec<u32>, Vec<u32>, Vec<u32>, Vec<u32>) = (a, b, e1, e2, r, x);
    let env = ExecutorEnv::builder()
        .write(&input)
        .unwrap()
        .build()
        .unwrap();
    
    // obtain the default prover.
    let prover = default_prover();

    let now = Instant::now();
    // produce a receipt by proving the specified ELF binary.
    let receipt = prover.prove(env, ZKP_ENC_ELF).unwrap().receipt;
    let elapsed = now.elapsed();
    println!("ZKP STARK Enc Prove: {:.2?} ms", elapsed.as_millis());

    // output the receipt to a file
    let output_path = PathBuf::from(proof_path);
    let bin = bincode::serialize(&receipt).unwrap();
    fs::write(output_path, &bin)?;
    println!("ZKP STARK Enc Size: {} bytes", bin.len());

    Ok(())
}
