// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use methods::ZKP_ENC_ID;
use std::{error::Error, fs, path::PathBuf, env, time::Instant};
use risc0_zkvm::Receipt;

fn main() -> Result<(), Box<dyn Error>>{
    // use executable as: ./verifier m l k data_path proof_path
    let args: Vec<String> = env::args().collect();
    let m : usize = args[1].parse().unwrap();
    let l : usize = args[2].parse().unwrap();
    let k : usize = args[3].parse().unwrap();
    let data_path = &args[4];
    let proof_path = &args[5];

    // read the JSON data to vector
    let data = fs::read_to_string(PathBuf::from(data_path))?;
    let data = json::parse(&data).unwrap();

    // init the vectors
    let mut c1 : Vec<u32> = Vec::new();
    let mut c2 : Vec<u32> = Vec::new();

    // load the data from JSON
    for i in 0..k{
        c1.push(data["c_1"][i].as_u32().unwrap());
    }
    for i in 0..m*l{
        c2.push(data["c_2"][i].as_u32().unwrap());
    }

    // load the receipt file
    let receipt_data = fs::read(PathBuf::from(proof_path)).unwrap();
    let receipt: Receipt = bincode::deserialize(&receipt_data).unwrap();

    let now = Instant::now();
    // verify the receipt file
    receipt.verify(ZKP_ENC_ID).expect("Verification failed!");
    let elapsed = now.elapsed();
    println!("ZKP STARK Enc Verify: {:.2?} ms", elapsed.as_millis());

    // compare the results
    // let (c_1, c_2) = receipt.journal.decode::<(Vec<u32>, Vec<u32>)>().unwrap();
    // if c_1 == c1 && c_2 == c2 {
    //     println!("Encryption verified!");
    // } else {
    //     println!("Encryption verification failed: results do not match!");
    // }
    Ok(())
}
